version: "3.1"

services:
  #    db:
  #        image: mysql:8.0
  #        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  #        environment:
  #            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  #            MYSQL_DATABASE: app

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

#  bot:
#    build: .
#    ports:
#      - "5000:5000"

  dockerhost:
    image: qoomon/docker-host:2.3.0
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]

